syntax = "proto3";

message Void {}
message Task {
  string id = 1;
  string title = 2;
  string description = 3;
  bool is_completed = 4;
  string date = 5;
  string responsible = 6;
}
message TaskID {
  string id = 1;
}
message TaskList {
  repeated Task tasks = 1;
}
service TaskService {
  rpc CreateTask (Task) returns (TaskID);
  rpc ListAllTasks (Void) returns (TaskList);
  rpc UpdateTask (Task) returns (TaskID);
  rpc DeleteTask (TaskID) returns (Void);
  rpc FinishTask (TaskID) returns (TaskID);
}