# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"\x06\n\x04Void\"i\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\x12\x13\n\x0bresponsible\x18\x06 \x01(\t\"\x14\n\x06TaskID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x08TaskList\x12\x13\n\x04list\x18\x01 \x03(\x0b\x32\x05.Task2\x95\x01\n\x03\x41PI\x12\x17\n\x07\x41\x64\x64Task\x12\x05.Task\x1a\x05.Task\x12\x1b\n\x07ListAll\x12\x05.Void\x1a\t.TaskList\x12\x1c\n\nUpdateTask\x12\x07.TaskID\x1a\x05.Task\x12\x1c\n\nDeleteTask\x12\x07.TaskID\x1a\x05.Task\x12\x1c\n\nFinishTask\x12\x07.TaskID\x1a\x05.Taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=15
  _globals['_VOID']._serialized_end=21
  _globals['_TASK']._serialized_start=23
  _globals['_TASK']._serialized_end=128
  _globals['_TASKID']._serialized_start=130
  _globals['_TASKID']._serialized_end=150
  _globals['_TASKLIST']._serialized_start=152
  _globals['_TASKLIST']._serialized_end=183
  _globals['_API']._serialized_start=186
  _globals['_API']._serialized_end=335
# @@protoc_insertion_point(module_scope)
